apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 15.4.4
    chart: kube-prometheus-stack
    helm:
     parameters:
      - name : grafana.ingress.enabled
        value : "true"
      - name : grafana.ingress.annotations.kubernetes\.io/ingress\.class
        value : nginx
      - name : grafana.ingress.annotations.external-dns\.alpha\.kubernetes\.io/hostname
        value : grafana.abs-cloud.nl
      - name: grafana.ingress.hosts[0]
        value: grafana.abs-cloud.nl
      - name: grafana.ingress.tls[0].secretName
        value: grafana-abs-cloud-nl
      - name: grafana.ingress.tls[0].hosts[0]
        value: grafana.abs-cloud.nl
      - name: grafana.persistence.type
        value: pvc
      - name: grafana.persistence.enabled
        value: "true"
      - name: grafana.persistence.storageClassName
        value: rook-ceph-block
      - name: grafana.persistence.accessModes[0]
        value: ReadWriteOnce
      - name:  grafana.persistence.size
        value: 20Gi
      - name: grafana.grafana\.ini.server.root_url
        value: https://grafana.abs-cloud.nl/grafana/
      - name: grafana.grafana\.ini.server.serve_from_sub_path
        value: "true"
      - name: grafana.grafana\.ini.auth\.gitlab.enabled
        value: "true"
      - name: grafana.grafana\.ini.auth\.gitlab.allow_sign_up
        value: "true"
      - name: grafana.grafana\.ini.auth\.gitlab.scopes
        value: read_api
      - name: grafana.grafana\.ini.auth\.gitlab.auth_url
        value: https://gitlab.abs-cloud.nl/oauth/authorize
      - name: grafana.grafana\.ini.auth\.gitlab.token_url
        value: https://gitlab.abs-cloud.nl/oauth/token
      - name: grafana.grafana\.ini.auth\.gitlab.api_url
        value: https://gitlab.abs-cloud.nl/api/v4
      - name: grafana.grafana\.ini.auth\.gitlab.client_id
        value: 19053ac7d6edb28b651ce9f0600242bf10ab620332427407ac24474347069e63
      - name: grafana.grafana\.ini.auth\.gitlab.client_secret
        value: 0b7e47ebfe16375cf92800ed8aad3fc457c29e92dbf4fdf0691c2ef81cb94cf9
      - name: grafana.plugins[0]
        value: vonage-status-panel
      - name: grafana.sidecar.dashboards.provider.foldersFromFilesStructure
        value: "true"
      - name: grafana.sidecar.dashboards.folderAnnotation
        value: k8s-sidecar-target-directory
      - name: grafana.sidecar.dashboards.annotations.k8s-sidecar-target-directory
        value: /tmp/dashboards/kubernetes
      - name: grafana.grafana\.ini.auth\.anonymous.enabled
        value: "true"
      - name: grafana.grafana\.ini.auth\.anonymous.org_name
        value: "Main Org."
      - name: grafana.grafana\.ini.auth\.anonymous.org_role
        value: Viewer
      - name: grafana.grafana\.ini.security.allow_embedding
        value: "true"
      # - name: grafana.additionalDataSources[0].name
      #   value: Prometheus-Rook
      # - name: grafana.additionalDataSources[0].type
      #   value: prometheus
      # - name: grafana.additionalDataSources[0].access
      #   value: proxy
      # - name: grafana.additionalDataSources[0].org_id
      #   value: "1"
      # - name: grafana.additionalDataSources[0].url
      #   value: http://rook-prometheus.rook-ceph:9090
      # - name: grafana.additionalDataSources[0].jsonData.tlsSkipVerify
      #   value: "true"
      # - name: grafana.additionalDataSources[0].jsonData.timeInterval
      #   value: "5s"
      # - name: grafana.additionalDataSources[0].version
      #   value: "1"
      # - name: grafana.additionalDataSources[0].editable
      #   value: "true"
      - name: prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.storageClassName
        value: rook-ceph-block
      - name: prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.accessModes[0]
        value: ReadWriteOnce
      - name: prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.resources.requests.storage
        value: 50Gi
      - name: prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues
        value: "false"
      - name: prometheus.prometheusSpec.serviceMonitorSelector
        value: ""
      - name: kubeEtcd.endpoints[0]
        value: "10.14.0.33"
      - name: kubeEtcd.endpoints[1]
        value: "10.14.0.2"
      - name: kubeEtcd.endpoints[2]
        value: "10.14.0.93"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
