apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - certificate.yaml
- serving-core-v0_23_0.yaml
- https://github.com/knative/net-istio/releases/download/v0.23.0/net-istio.yaml
# - net-istio-v0_22_0.yaml
# - eventing-core-v0_22_0.yaml # Eventing is optional
# - monitoring/
